services:
  file-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-client
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    working_dir: /app
    command: python app.py
    volumes:
      - /srv/archive:/data/archive
      - ./:/app:ro
